// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDW55eBlPNGUqEodaP-3_Y-sG7Z-6bV00',
    appId: '1:40071262339:web:af5176f0e3b88ac1502bb6',
    messagingSenderId: '40071262339',
    projectId: 'prakflutterfirebase-20110012',
    authDomain: 'prakflutterfirebase-20110012.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-20110012.appspot.com',
    measurementId: 'G-VB4R0MJJPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2c-1wBeX8O6otg0WF2ktOZ6mVEsubio',
    appId: '1:40071262339:android:79cdf96abb7b9248502bb6',
    messagingSenderId: '40071262339',
    projectId: 'prakflutterfirebase-20110012',
    storageBucket: 'prakflutterfirebase-20110012.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOetm400wjSP7atoWmUlHhurgZj947ogU',
    appId: '1:40071262339:ios:2b0f17241a7a9f8d502bb6',
    messagingSenderId: '40071262339',
    projectId: 'prakflutterfirebase-20110012',
    storageBucket: 'prakflutterfirebase-20110012.appspot.com',
    androidClientId: '40071262339-u52hvkvfreeuji5csj3ua51iceu0gtiv.apps.googleusercontent.com',
    iosClientId: '40071262339-1ngk2q180fmv176nep32nqjt55nn08k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeAppStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOetm400wjSP7atoWmUlHhurgZj947ogU',
    appId: '1:40071262339:ios:2b0f17241a7a9f8d502bb6',
    messagingSenderId: '40071262339',
    projectId: 'prakflutterfirebase-20110012',
    storageBucket: 'prakflutterfirebase-20110012.appspot.com',
    androidClientId: '40071262339-u52hvkvfreeuji5csj3ua51iceu0gtiv.apps.googleusercontent.com',
    iosClientId: '40071262339-1ngk2q180fmv176nep32nqjt55nn08k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeAppStore',
  );
}
